### ISSUE TITLE
Are the addons going to be updated to support newer helm versions with the impending gcr.io registry change?

### ISSUE THREAD

**Issue by that-kampe-steak** [aws-ia/terraform-aws-eks-blueprints-addons#120]
Addons seemingly will expire soon with no recourse as these are hard coded in the repository.  Is there a plan to manage this? 

https://kubernetes.io/blog/2023/03/10/image-registry-redirect/

**Comment by bryantbiggs** [comment]
`metrics-server` resolved in https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/122
