### ISSUE TITLE
ArgoCD: create applications with custom plugins

### ISSUE THREAD

**Issue by mkantzer** [aws-ia/terraform-aws-eks-blueprints-addons#127]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

I'd like to use the ArgoCD module to deploy an ArgoCD `application` that uses a [Config Management Plugin](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/) to render manifests.  

#### Describe the solution you would like

Right now, the plugin only supports `type`s of `kustomize` and `helm`. I suggest adding the ability to use _any_ string as a `type`, which, if set to a value other than `kustomize` or `helm`, would populate the `Application`'s `spec.source.plugin.name` value, and also _not_ set any `spec.source.kustomize` or `spec.source.helm` values.

It would also be good to have the ability to set `spec.source.plugin.env` and `spec.source.plugin.parameters`.

Note: I am _not_ asking for specific capabilities to _create_ the plugins themselves: while that _would_ be useful, it's entirely possible with the current system [(example)](https://github.com/mkantzer/k8splayground-core-infra/blob/ef53cd045fd65ab16c218a51cac9566c6c62b26a/argocd.tf#L42-L87). Being able to _consume_ them in an `application` is what I'm requesting.

#### Describe alternatives you have considered

I've considered just creating the manifest outside of the module, and I've also considered using an app-of-app-of-apps to bootstrap up to having applications that use the plugin. Bother are messier, and leave argo bootstrapping scattered. 

#### Additional context

- [ArgoCD Config Management Plugin docs](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/)
- [ArgoCD application.yml plugin configuration](https://github.com/argoproj/argo-cd/blob/b96bf6b49e0935e9f65a5219627f8652471f0433/docs/operator-manual/application.yaml#L121-L138)

**Comment by bryantbiggs** [comment]
thank you for the issue! At this time we are re-evaluating the integration between Terraform and GitOps operators like ArgoCD. We have removed the integration from the current project and will be tracking all feedback input in #114 while developing the next iteration of this integration
