### ISSUE TITLE
Karpenter not creating nodes

### ISSUE THREAD

**Issue by BrandonEscamilla** [aws-ia/terraform-aws-eks-blueprints-addons#139]
[X] ✋ I have searched the open/closed issues and my issue is not listed.
Please describe your question here
When using Karpenter, the nodes are not being created and the logs says this:

`
"You are not authorized to perform this operation. Encoded authorization failure message: HZ_v......"
`

Thank you in advance!

```
karpenter = {
    repository_username = data.aws_ecrpublic_authorization_token.token.user_name
    repository_password = data.aws_ecrpublic_authorization_token.token.password
}
karpenter_instance_profile = {
    name = module.karpenter.instance_profile_name
    iam_role_name = module.eks.fargate_profiles["karpenter"].iam_role_name
}

karpenter_enable_spot_termination = true
```

I am using this configuration.

Provide a link to the example/module related to the question
Additional context

**Comment by bryantbiggs** [comment]
hi @BrandonEscamilla - could you please provide a full reproduction that we can deploy and demonstrate this error plus the steps you took to re-create the error?

**Comment by bryantbiggs** [comment]
closing for now - please feel free to respond with additional details and we can take a look
