### ISSUE TITLE
aws_node_termination_handler issue when enabled

### ISSUE THREAD

**Issue by BrandonEscamilla** [aws-ia/terraform-aws-eks-blueprints-addons#140]
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here
When enable_aws_node_termination_handler is enabled, i am getting the following error:

```
module.eks_blueprints_kubernetes_addons.module.aws_node_termination_handler.helm_release.this[0]: Still creating... [5m1s elapsed]
╷
│ Warning: Helm release "aws-node-termination-handler" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_node_termination_handler.helm_release.this[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/eks-blueprints-addon/main.tf line 9, in resource "helm_release" "this":
│    9: resource "helm_release" "this" {
│ 
╵
╷
│ Error: timed out waiting for the condition
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_node_termination_handler.helm_release.this[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/eks-blueprints-addon/main.tf line 9, in resource "helm_release" "this":
│    9: resource "helm_release" "this" {
│ 
╵
╷
│ Error: creating IAM Policy aws-node-termination-handler-20230419160214074700000007: MalformedPolicyDocument: Policy statement must contain resources.
│       status code: 400, request id: bdfe8443-557e-4aeb-8bd4-0ae038c21c3d
│ 
│   with module.eks_blueprints_kubernetes_addons.module.aws_node_termination_handler.aws_iam_policy.this[0],
│   on .terraform/modules/eks_blueprints_kubernetes_addons/modules/eks-blueprints-addon/main.tf line 237, in resource "aws_iam_policy" "this":
│  237: resource "aws_iam_policy" "this" {
│ 
```

Thank you in advance!

**Comment by wasd171** [comment]
@BrandonEscamilla I have the same issue, how did you solve it?

**Comment by armujahid** [comment]
I think this should be reopened.
https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/170#issuecomment-1837388774

**Comment by bryantbiggs** [comment]
> since we shouldn't use NTH with managed node group and even with karpenter

Correct 

Apologies but I'm not following what the issue is then? If you wish to utilize node-termination-handler, you will need to tell NTH which autoscaling groups it should be monitoring for health events https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/0e9d6c9b7115ecf0404c377c9c2529bffa56d10d/main.tf#L1606C21-L1606C58

If there are no ASGs (self-managed), there is no point in having NTH deployed in the cluster. Correct me if I am wrong but this sounds like a user configuration issue and not a module issue

**Comment by armujahid** [comment]
@bryantbiggs you are right. Apologies it's not an issue. I was using NTH in a cluster with self managed groups and forgot to remove that while migrating to managed node groups. I noticed this error today while upgrading from v4 to v5 blueprints.
