### ISSUE TITLE
Gracefully handle scenario where eks cluster is a "Local Cluster" deployment thus oidc_provider_arn input will be empty

### ISSUE THREAD

**Issue by FireballDWF** [aws-ia/terraform-aws-eks-blueprints-addons#152]
## Versions

- Module version [Required]: ref=c0a5dad79758e52821af8c41c9c3719570c81d08

- Terraform version: Terraform v1.4.6
- Provider version(s):
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.65.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.20.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4

## Reproduction Code [Required]

https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/examples/outposts)
plus
```
module "eks_blueprints_addons" {
  source     = "github.com/aws-ia/terraform-aws-eks-blueprints-addons.git?ref=c0a5dad79758e52821af8c41c9c3719570c81d08"

  cluster_name      = module.eks.cluster_name
  cluster_endpoint  = module.eks.cluster_endpoint
  cluster_version   = module.eks.cluster_version
  oidc_provider_arn = module.eks.oidc_provider_arn

  enable_aws_node_termination_handler   = true
  aws_node_termination_handler_asg_arns = [for asg in module.eks.self_managed_node_groups : asg.autoscaling_group_arn]

}
```

terraform init
terraform apply -auto-approve

## Expected behaviour

Either a graceful handling of the lack of oidc_provider_arn for add-on's which actually require it, or actual deployment of any add-on's which don't require OIDC support.

## Actual behaviour
```

│ Error: Invalid function argument
│ 
│   on .terraform/modules/eks_blueprints_addons.aws_node_termination_handler/main.tf line 142, in data "aws_iam_policy_document" "assume":
│  142:         variable = "${replace(statement.value.provider_arn, "/^(.*provider/)/", "")}:sub"
│     ├────────────────
│     │ statement.value.provider_arn is null
│ 
│ Invalid value for "str" parameter: argument must not be null.
╵
╷
│ Error: Invalid function argument
│ 
│   on .terraform/modules/eks_blueprints_addons.aws_node_termination_handler/main.tf line 149, in data "aws_iam_policy_document" "assume":
│  149:         variable = "${replace(statement.value.provider_arn, "/^(.*provider/)/", "")}:aud"
│     ├────────────────
│     │ statement.value.provider_arn is null
│ 
│ Invalid value for "str" parameter: argument must not be null.
```

**Comment by bryantbiggs** [comment]
I don't know how valuable of a change that would be here provided local clusters on Outposts do not support IRSA. Part of the main motivation of this module is to make the IRSA process as seamless as possible for users without the need to track down permissions, how to attach, etc.

**Comment by FireballDWF** [comment]
Just expecting graceful handling of the null, check up front that if provider_arn is null, return error that a valid arn is required.

**Comment by bryantbiggs** [comment]
I'm not following - the `oidc_provider_arn` is a required variable (no default provided), and OIDC/IRSA is not supported on local clusters on Outposts - I'm not following what you mean by `graceful handling` - you will get an error no matter what since its not supported

**Comment by FireballDWF** [comment]
Someone who is not aware of OIDC/IRSA not being supported on local clusters is likely to follow example code like
``` 
 oidc_provider_arn = module.eks.oidc_provider_arn
```
from https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/90a70ba07eebdd2af91047798c0887361cfe31d8/tests/complete/main.tf#L107 which will pass the required variable test yet will get the reported error. 

How about adding a validation block to the variable oidc_provider_arn?  At minimum, check for non-null.  Even better, check if string match a pattern like arn:aws:iam::[[:digit:]]{12}:oidc-provider/oidc.eks.+

**Comment by fcarta29** [comment]
Fully understand the ask around validation for empty/null on the arn input. With that I also agree with @bryantbiggs that there should be an understanding when EKS Blueprints are being used for local clusters on Outpost that certain restrictions apply like IAM roles for service accounts not being supported. Ultimately this is an invalid manifest so adding validation for the field would only mask the real issue of improper configuration. 

Please see documentation for [IAM roles](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) 

"You can't use IAM roles for service accounts with [local clusters for Amazon EKS on AWS Outposts](https://docs.aws.amazon.com/eks/latest/userguide/eks-outposts-local-cluster-overview.html)."
