### ISSUE TITLE
Doc page showing list of EKS Blueprints for Terraform Addons supported with Graviton (ARM64).

### ISSUE THREAD

**Issue by elamaran11** [aws-ia/terraform-aws-eks-blueprints-addons#161]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Doc page showing list of EKS Blueprints for Terraform Addons supported with Graviton (ARM64). This would help our customers to pick and choose ARM64 supported addons while selecting their day 2 ops tooling.

#### Describe the solution you would like

Doc page showing list of EKS Blueprints for Terraform Addons supported with Graviton (ARM64). This would help our customers to pick and choose ARM64 supported addons while selecting their day 2 ops tooling while running their environment with Graviton on EKS.

#### Describe alternatives you have considered

None

#### Additional context

None

**Comment by elamaran11** [comment]
@bryantbiggs Awesome work!

**Comment by bryantbiggs** [comment]
@elamaran11 we'll add some more detailed docs soon for each addon and probably a code snippet to better demonstrate how to use x86_64/amd64 and/or arm64 images

**Comment by elamaran11** [comment]
Wonderful @bryantbiggs !
