### ISSUE TITLE
AWS managed addon `ebs-csi-driver` missed IRSA

### ISSUE THREAD

**Issue by hustshawn** [aws-ia/terraform-aws-eks-blueprints-addons#186]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Right now when people enable the `aws-ebs-csi-driver` under `eks_addon`, it only create the `aws_eks_addon` resource without proper IAM permissions. This way the eks managed addons would assume this addon inherit permissions from the worker node.  
People may expect once enabled the addon, there shoud be the correspoinding IRSA created for it.

#### Describe the solution you would like

Create an IRSA for the addon when customer choose to enable it. The IAM role should simply have a AWS managed policy `arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy` as mentioned in [EKS document](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html#workloads-add-ons-available-eks).

#### Describe alternatives you have considered

So far, both  [terraform-aws-eks module](https://github.com/terraform-aws-modules/terraform-aws-eks) and this module has option to enable aws managed eks addon. I would like to see which place is better to have the feature to implement?

**Comment by bryantbiggs** [comment]
Both this module and the `terraform-aws-eks` module implement the EKS addons in the same manner - we can look at improving the documentation to make it more clear that EKS addons that require IRSA will require users to add the appropriate IRSA resources for the addon

**Comment by momelod** [comment]
for what it's worth, here is how i was able to attache the aforementioned policy:

```
resource "aws_iam_role_policy_attachment" "AmazonEBSCSIDriverPolicy" {
  role       = module.eks.cluster_iam_role_name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
}
```

**Comment by bryantbiggs** [comment]
The recommended way would be to use IRSA and provide the addon configuration the IRSA ARN like https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/c01ea014c83943211b985983e579ff83cb18b846/examples/stateful/main.tf#L208 

With IRSA defined below https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/c01ea014c83943211b985983e579ff83cb18b846/examples/stateful/main.tf#L410-L426

**Comment by hustshawn** [comment]
Hi @bryantbiggs , yes that's the way I am currently doing and recommend to customers as well. 

I understand currently it just create the (eks) addon resources. But still the original idea is that customer should just choose to enable the addon, and the module take care of all the configurations including the IRSA, as the it should be standard for all the customers. 

So I am just wondering what could be a better way to implement this? I supose we should have an overall design pattern for these AWS managed addons with IRSA. then we can probably discuss how we implement.
