### ISSUE TITLE
ALB Controller unable to search for certificates in AWS Certificate Manager

### ISSUE THREAD

**Issue by wfrced** [aws-ia/terraform-aws-eks-blueprints-addons#198]
## Description

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

The included IAM policy for ALB controller sets incorrect permissions for `AllowGetCertificates` statement. It prevents ALB controller from accessing ACM certificates and makes it impossible to use the certificate search functionality, resulting in errors like `AccessDeniedException: User: arn:aws:sts::433222222257:assumed-role/alb-controller-20230620120130875800000002/1687883887660094198 is not authorized to perform: acm:ListCertificates because no identity-based policy allows the acm:ListCertificates action"`

This is a result of limiting the statement to the following resources:

```
"arn:${local.partition}:acm:${local.region}:${local.account_id}:*",
"arn:${local.partition}:acm:${local.region}:${local.account_id}:certificate/*"
```

The actions do not take limits and require a wildcard (`"*"`) resource access.

## Versions

- Module version [Required]: v1.1.0 (currently latest)

- Terraform version: `Terraform v1.5.1 on linux_amd64`
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v5.4.0
+ provider registry.terraform.io/hashicorp/helm v2.10.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.21.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

## Reproduction Code [Required]

```
module "addons_alb_controller" {
  source  = "aws-ia/eks-blueprints-addons/aws"
  version = "1.1.0"

  cluster_name      = module.eks.eks_cluster_id
  cluster_endpoint  = module.eks.eks_cluster_endpoint
  cluster_version   = module.eks.eks_cluster_version
  oidc_provider_arn = module.eks.eks_cluster_identity_oidc_issuer_arn

  enable_aws_load_balancer_controller = true
  aws_load_balancer_controller = {}

  tags = var.tags
}
```

## Expected behaviour

ALB controller is able to search for SSL certificates in AWS Certificate Manager (required for SSL Ingress).

## Actual behaviour

ALB controller fails to search for certificates in ACM with the following error:

`AccessDeniedException: User: arn:aws:sts::433222222257:assumed-role/alb-controller-20230620120130875800000002/1687883887660094198 is not authorized to perform: acm:ListCertificates because no identity-based policy allows the acm:ListCertificates action"`

## Additional context

PR that fixes this error: https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/196

**Comment by bryantbiggs** [comment]
could you explain a bit more about your setup - are the ACM certs in the same account and same region as the cluster?

**Comment by wfrced** [comment]
Yes, I'm using the same Terraform provider for ACM resources. Double-checked right now.
[Here's how a correct permission looks like in Policy Simulator](https://i.imgur.com/hcENDh9.png)
[And here's the result with the current policy](https://i.imgur.com/4Dizycx.png)

**Comment by ManuelMueller1st** [comment]
We experience the same problem. It can be easily reproduced by creating an IAM user with the same policy. According to the AWS documentation, ListCertificates has no resource types.

https://docs.aws.amazon.com/service-authorization/latest/reference/list_awscertificatemanager.html#awscertificatemanager-certificate
