### ISSUE TITLE
bug: CSI secret provider + driver can't render resouces in kube-system

### ISSUE THREAD

**Issue by MaiCabrera** [aws-ia/terraform-aws-eks-blueprints-addons#22]
## Description

Currently the new csi-secret-store provider is using the aws eks-charts version.  Currently the chart itself requires just being able to deploy into the 'kube-system` the actual resource (see below)

```yaml
resource "kubernetes_namespace_v1" "csi_secrets_store_provider_aws" {
  metadata {
    name = local.namespace
  }
}
```
forces as if it requires the namespace. which seems overkill. 

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

**Comment by askulkarni2** [comment]
Fixed in #53
