### ISSUE TITLE
Previously Supported add-ons not supported on new implementation. 

### ISSUE THREAD

**Issue by yardenw-terasky** [aws-ia/terraform-aws-eks-blueprints-addons#230]
Hey, I can see that some of the add-ons that were supported on the older version of EKS Blueprints are not supported on EKS Blueprints add-on's new implementation. 

For example: 
Amazon Prometheus, Calico, Keda, and some others. 

Is there a plan to add all of the previously supported modules to the new implementation?

**Comment by askulkarni2** [comment]
No, please see https://aws-ia.github.io/terraform-aws-eks-blueprints-addons/main/helm-release/. For AMP you can use https://registry.terraform.io/modules/terraform-aws-modules/managed-service-prometheus/aws/latest.
