### ISSUE TITLE
AWS cluster node termination handler crashing

### ISSUE THREAD

**Issue by jeenadeepak** [aws-ia/terraform-aws-eks-blueprints-addons#235]
## Description

I have recently migrate terraform code from 4 to 5, While installing adding ode termination handler throwing I AM throwing policy error

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- EKS version: 1.27
- Module version [Required]: 1.7.0

- Terraform version:  1.5.4

- Provider version(s):  5.13.1

## Reproduction Code [Required]

module "eks_blueprints_addons" {
source = "aws-ia/eks-blueprints-addons/aws"
version = "~> 1.7.0" 

cluster_name      = module.eks.cluster_name
cluster_endpoint  = module.eks.cluster_endpoint
cluster_version   = module.eks.cluster_version
oidc_provider_arn = module.eks.oidc_provider

eks_addons = {
    aws-ebs-csi-driver = {
        most_recent = true
    }
    coredns = {
        most_recent = true
    }
    vpc-cni = {
        most_recent = true
    }
    kube-proxy = {
        most_recent = true
    }
   }

   enable_aws_load_balancer_controller    = var.enable_eks_aws_load_balancer_controller
   enable_metrics_server                  = var.enable_eks_metrics_server
   enable_cluster_autoscaler              = var.enable_eks_cluster_autoscaler

   enable_cert_manager                    = var.enable_eks_cert_manager
   cert_manager_route53_hosted_zone_arns  = ["arn:aws:route53:::hostedzone/${local.route53_hosted_zone_id}"]

   enable_aws_node_termination_handler    = var.enable_aws_node_termination_handler
}

## Actual behaviour

<img width="1326" alt="Screenshot 2023-08-20 at 11 42 08 AM" src="https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/assets/106949078/ff3fbb28-a440-42c6-993b-0b639a74cac5">

**Comment by jeenadeepak** [comment]
I am using "aws managed node" for eks, it seems this is not required for aws managed node, as asg are not available for "aws managed node"

**Comment by bryantbiggs** [comment]
NTH is not required for managed nodegroups, and yes managed nodegroups do create ASGs

**Comment by bryantbiggs** [comment]
see https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/a780ef35f69eec02fddcab183067784d32ef3616/tests/complete/main.tf#L162 for self-managed nodegroup example
