### ISSUE TITLE
terraform-aws-eks-blueprints-addons could be made more useful with submodules

### ISSUE THREAD

**Issue by joaocc** [aws-ia/terraform-aws-eks-blueprints-addons#246]
Having spend some time recently migrating to v5.0 (both of independent addons ("blueprints-addon" - singular) and the bundled version (aka, the monolith-that-is-smaller-than-v4, with "blueprint-addons" name), and also after #221, I can't help but feel that the current approach of v5.0 can be made better by splitting "the monolith" into submodules.

Proposal A
1. all the add-ons being deployed would be moved to /modules/ so they could also be used independently;
2. end-users would still see a single unified variables.tf interface much like before; migrations could be achieved via "moved" blocks at the top level, for backwards compat;
3. the main file would become a bit easier to maintain in the future;
 
Proposal B
* same as A but with the ability to add multiple instances of the same module (think ingress or external-dns) indexed as map (so they can be removed without affecting others);

Personally, I see the A1 point as being the bigger benefit, as the current v5.0 approach adds value on some of the modules (where it does more than simply passing values around) but keeps those goodies in the monolith.
Of submodules are implemented, then Proposal B is not even needed, as people might simply include the submodules they prefer.

**Comment by schwichti** [comment]
Relevant: https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/221

**Comment by schwichti** [comment]
Have overlooked that you already mentioned it

**Comment by joaocc** [comment]
@schwichti I still think that submodules in addons (v5) will be more sustainable, as the number will tend to grow larger with time, and make main.tf even bigger.
There are certainly some downsides due to the fact that changes happen in different files, and we have a potentially larger number of files (unless we collapse variables.tf, outputs.tf and main.tf in a single file), but that decision can be left to the "maintainer" of each addon. 
On the other hand, all scenarios where you need multiple instances of an addon become much simpler (currently the option is to include the big addon multiple times). And in terms of migration path, the introduction of modules can be made incrementally, adding "moved" blocks on each module that has been moved to independent file, to make reduce impact on people's existing state files
