### ISSUE TITLE
Allow addons to work with AWS provider >=4.47 (as before)

### ISSUE THREAD

**Issue by joaocc** [aws-ia/terraform-aws-eks-blueprints-addons#247]
When trying to migrate from aws-eks-blueprint-addons from v4 to v5, it started requiring hashicorp/aws from the former ">= 4.47".
This means that this forces migration of the underlying aws provider, which is a much larger endeavour and carries a much bigger risk.
Unless there is a specific driver for this, it's much simpler to continue supporting hashicorp/aws ">= 4.47".

**Comment by bryantbiggs** [comment]
[These arguments](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/61ca8c13091d6ac1a53eda88b5ef4d88a17859bd/main.tf#L2188-L2189) are only supported starting on [v5.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#500-may-25-2023) of the AWS provider - this is what dictates the minimum version and therefore we cannot support anything less than this version

**Comment by joaocc** [comment]
Pls ignore prev comment. The issue is on the left side of the assignment. No choice than to use the fork until we upgrade.
Thanks!
