### ISSUE TITLE
enable  csi_secrets_store_provider_aws using gitops

### ISSUE THREAD

**Issue by chakch** [aws-ia/terraform-aws-eks-blueprints-addons#25]
## Description

I want to deploy the csi_secrets_store_provider_aws but when I put argocd_manage_add_ons=true I can't choose which addons is deployed using terraform or argocd 

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by bryantbiggs** [comment]
thank you for the issue! At this time we are re-evaluating the integration between Terraform and GitOps operators like ArgoCD. We have removed the integration from the current project and will be tracking all feedback input in #114 while developing the next iteration of this integration
