### ISSUE TITLE
Setting relevant subnet tags for Karpenter and ALBC

### ISSUE THREAD

**Issue by blakepettersson** [aws-ia/terraform-aws-eks-blueprints-addons#257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

The need not to explicitly create EC2 tag resources on subnets.

When a customer creates an EKS cluster, we need to ensure that for both `aws-load-balancer-controller` and for `karpenter` that the correct tags have been set on the subnets used. Due to... shall we say, a sub-optimal, networking configuration we can't do this where it really belongs (i.e. in the VPC configuration).

#### Describe the solution you would like

In the case of Karpenter, I'd like to pass in a list of subnets which would basically set this EC2 tag:

```terraform
resource "aws_ec2_tag" "karpenter_tag" {
  for_each    = local.all_subnets
  resource_id = each.key
  key         = "karpenter.sh/discovery/${module.cluster.cluster_id}"
  value       = module.cluster.cluster_id
}
``` 

In the case of `aws-load-balancer-controller`, I'd like for these tags to be set

```terraform
resource "aws_ec2_tag" "lb_tag" {
  for_each    = local.all_subnets
  resource_id = each.key
  key         = "kubernetes.io/cluster/${module.cluster.cluster_id}"
  value       = "shared"
}
```

As well as setting this tag (which sadly has to be a `null_resource`)

```terraform
# This needs to be a null_resource so that a `terraform destroy` doesn't ruin things for other clusters which may be
# using the same subnets (since removing a tag would prevent all clusters from working properly)
resource "null_resource" "subnet_tags" {
  # Changes to any subnet requires the relevant tags to be set to be sure that load balancers can properly run
  triggers = {
    subnets = join(",", local.all_subnets)
  }

  provisioner "local-exec" {
    # Create the kubernetes.io/role/internal-elb: 1 tag on all the k8s subnets if they do not already have the said tag
    command = "aws ec2 create-tags --resources ${join(" ", local.all_subnets)} --tags Key='kubernetes.io/role/internal-elb',Value='1' --region ${local.aws_region}"
  }
}
```

This is for internal ALBs, so I guess there needs to be some parameterisation for public LBs, or subnets which are not supposed to be shared between subnets. 

#### Describe alternatives you have considered

Keeping this outside of this module, but it'd be nice for this to be abstracted away.

**Comment by bryantbiggs** [comment]
the tags required by Karpenter will be updated in #284 - please follow that issue for the next iteration of Karpenter changes
