### ISSUE TITLE
Karpenter Role Permissions for GetProduct

### ISSUE THREAD

**Issue by dereckmartin** [aws-ia/terraform-aws-eks-blueprints-addons#258]
## Description

Looks like the permissions for the role need to be updated to include pricing:GetProducts

`AccessDeniedException: User: <omitted> is not authorized to perform: pricing:GetProducts with an explicit deny in a service control policy`

https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/809affc35191c2a9800dc60ccb09dab17818d5d6/main.tf#L2743

If your request is for a new feature, please use the `Feature request` template.

- [ * ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [~1.0]:

**Comment by bryantbiggs** [comment]
We have the permission for this API call here https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/809affc35191c2a9800dc60ccb09dab17818d5d6/main.tf#L2776-L2779

From your error message, it looks like your service control policy(s) are blocking this API call - see last part of your error message
> with an explicit deny in a service control policy

**Comment by bryantbiggs** [comment]
closing for now, let us know if you have any additional questions
