### ISSUE TITLE
aws_caller_identity and aws_partition called for all modules, even if disabled

### ISSUE THREAD

**Issue by joaocc** [aws-ia/terraform-aws-eks-blueprints-addons#261]
## Description
Current approach of a single-monolith file combined with the use of the "create" pattern cause "aws_caller_identity" and "aws_partition" to be called/instantiated for each and every module included in the file, even if they are not used.

This creates many unnecessary resources in terraform state (and confuses plans) when the module is used multiple times (say for multiple ingresses in same cluster, or multiple external-dns for multiple providers).

These are called once per included module as "aws-ia/terraform-aws-eks-blueprints-addon" includes them, and is instantiated with create=false.
To prevent unnecessary calls/instantiation, unused modules should also be guarded with the "count = (enable_m ? 1 : 0)" pattern.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 1.8.x and 1.9.x

## Reproduction Code [Required]
module "this" {
  source  = "aws-ia/eks-blueprints-addons/aws"
  version = "1.9.0"
}

## Expected behaviour
"aws_caller_identity" and "aws_partition" only called once for the "addons" module, and only once for each enabled "addon" module.

## Actual behaviour
"aws_caller_identity" and "aws_partition" only called once for the "addons" module, and only once for each "addon" module, even the ones which are not enabled

**Comment by bryantbiggs** [comment]
Removing the bug label since this is down to the user implementation and not the module itself. Please provide a reproduction and we can take a look and help provide guidance

**Comment by joaocc** [comment]
Hi. With reference to addon module being brought to 1.1.1, this ticket no longer makes sense, as I no longer see impact of using either create or count. Closing. Thanks!
