### ISSUE TITLE
Combination of AWS LBC webhook & the change to Helm wait=false leads to lots of hidden failures

### ISSUE THREAD

**Issue by james-masson** [aws-ia/terraform-aws-eks-blueprints-addons#274]
## Description

This issue is a combination of:

* https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/233
* https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/main/tests/complete/main.tf#L150
* https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/206

We're building repeatable EKS installs with terraform, to provide turn-key clusters that are ready for our customers to use.

Using ELBs instead of NLB/ALB is not something that AWS should be encouraging in 2023, we don't want our customers to issue ELBs and then have a migration path off ELB in the near future.

If we choose to enable "mutation webhook" for ALBC on our installs, then due to the default `wait = false`, we *may*  (but not always) get a success from Terraform, but have a lot of hidden Helm fails behind the scenes. The failures will be quite random & I understand why. In most cases the failures are cosmetic, but they're not a good look for a newly presented cluster.

eg.
```
NAME                        	NAMESPACE       	REVISION	UPDATED                                	STATUS  	CHART                             	APP VERSION
ack-rds                     	ack-rds         	1       	2023-10-03 10:22:55.345946206 +0100 BST	deployed	rds-chart-1.1.4                   	1.1.4      
aws-for-fluent-bit          	kube-system     	1       	2023-10-03 10:22:51.385713485 +0100 BST	deployed	aws-for-fluent-bit-0.1.27         	2.31.11    
aws-load-balancer-controller	kube-system     	1       	2023-10-03 10:22:52.198362008 +0100 BST	deployed	aws-load-balancer-controller-1.6.0	v2.6.0     
cert-manager                	cert-manager    	1       	2023-10-03 10:22:51.290160968 +0100 BST	failed  	cert-manager-v1.12.3              	v1.12.3    
external-dns                	external-dns    	1       	2023-10-03 10:22:50.004422412 +0100 BST	deployed	external-dns-1.13.0               	0.13.5     
external-secrets            	external-secrets	1       	2023-10-03 10:22:50.709806203 +0100 BST	failed  	external-secrets-0.9.1            	v0.9.1     
```

So, in order to catch *real* failures in our own CI systems, we have to manually enable `wait = true` for everything - because we want to see where things actually fail.

And in order to make everything work correctly *every time*, we have to start doing our own ordering with multiple phase installs with `depends_on`, and lots of `terraform-aws-eks-blueprints-addon` vs "addons"

Despite what's said here https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/233#issuecomment-1712669436 - there's also a dependency on cert-manager too.

All of this makes this project a little redundant? Is this project not about standardising the commissioning work that nearly every EKS customer will have to do?

I understand why things may be non-optimal short-term, that's fine. I'm just after some assurances that this project has a plan for the future.

From the outside, seeing the combination of...
* disabling Helm install validation by default
* disabling a key integration of EKS because it's problematic to the project

... does not bode well.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 1.9.1

```
Terraform v1.5.5
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v5.6.2
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/helm v2.10.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.21.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

## Reproduction Code [Required]

Your own test code...

https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/main/tests/complete/main.tf

Without disabling the ALBC webhook & enabling `wait = true` for everything.

**Comment by bryantbiggs** [comment]
I believe the issue here stems from the use of trying to use Terraform to do application deployment (CD), which is not what it was designed to do nor well suited for. While we recognize that Terraform is used in this manner, as evident by the existence of this project, it is not our recommended approach for application management within Kubernetes/EKS clusters. That would be better handled by a GitOps controller such as FluxCD, ArgoCD, etc.

> So, in order to catch real failures in our own CI systems, we have to manually enable wait = true for everything - because we want to see where things actually fail.

This sort of conflicts with the way actions are performed within Kubernetes. The control loop that is used pervasively throughout Kubernetes is intended to resolve these types of challenges, as well as many other reasons. This is why we have made `wait = false` the default for addons - Terraform simply does the Helm install, and its up to that addons controller/operator to resolve itself and its dependencies. This matches some of the behavior of what a GitOps controller would do - where it does the install and then depending on what resolution/sync policy is utilized, it will either do nothing and simply report that the addon deployment is failing (if the controller does not resolve itself), or it will continuously re-apply the source manifests to keep trying to reach the desired state (think `terraform apply` repeatedly if drift is detected)

**Comment by bryantbiggs** [comment]
Thinking from a different perspective - if you were not using Terraform do perform deploy these addons, how would you solve the current situation?

**Comment by james-masson** [comment]
> While we recognize that Terraform is used in this manner, as evident by the existence of this project, it is not our recommended approach for application management within Kubernetes/EKS clusters. That would be better handled by a GitOps controller such as FluxCD, ArgoCD, etc.

Yes, I would prefer to manage K8s software outside of Terraform - and we do for the most part, including with the tools that you mention.

However, there are classes of K8s software that are closer to the infrastructure, and are tightly tied to it. Given that Terraform is used to provision this infrastructure, it makes sense to handle select low-level integration software with Terraform.

This has the advantage of:
* Changing dependent infrastructure & software together ( eg. new version of Controller-X requires new IAM permission Y)
* Not needing to pass changeable infrastructure references between your Terraform and your usual software GitOps flow ( separation of concerns & security boundaries between project staff )

To be honest, I thought this whole project was the recognition that this is a very standard way to deal with this particular problem.  I hoped this was an AWS Official way to do it, to save me re-inventing this wheel yet again for a new customer. 

> The control loop that is used pervasively throughout Kubernetes is intended to resolve these types of challenges, as well as many other reasons. This is why we have made wait = false the default for addons - Terraform simply does the Helm install, and its up to that addons controller/operator to resolve itself and its dependencies. 

This smells of avoiding the problem.

If I use ArgoCD to transition between state A and state B, I would expect that Argo would flag a failure.

Similarly with Terraform, I would expect to be notified of a failure in transition between A and B. This is what anyone who uses Terraform to do a task would expect by default.

What you're suggesting is that Terraform should succeed regardless despite the validity of input, and it's up to something else undefined to flag the problem. How do you test this yourself in CI? The current example deployment is racy, and will result in helm install fails occasionally with no warning in Terraform.

> Thinking from a different perspective - if you were not using Terraform do perform deploy these addons, how would you solve the current situation?

There are two different issues here.

1. ALBC installs causing ( mostly but not always temporary ) failures in other applications. There may be other applications in the implicitly supported stack that also do this.
2. Implicit ordering issues between Charts.

Fixing 1 requires the change to happen in a well bounded window of exclusivity ( of our control at least). If you were adding this change to a running EKS through Argo, you'd probably put this though in a commit on it's own.

However, that's not really viable for spinning up turn-key EKS clusters for other people - that exclusivity logic needs to be part of the commissioning system.

2 requires dependency management. Helm has a very standard way of handling that.

None of these problems are particularly difficult to solve in this codebase - but it does require the concept of optimal ordering for your supported software catalog, and not ignoring failures.

What worried me was that in stead of trying to solve these problem, they were being avoided.

**Comment by FernandoMiguel** [comment]
we too, went initially over the nightmare of managing all deployments of base addons via terraform. lots of `depends_on` and careful managing the uninstall process.
eventually we moved everything that was possible to argo, leaving terraform for only things where ACK is not available, and access to AWS data-sources, which we inject as git commits into argo deployments.
So for ex, for deploying AWS LBC via argo, terraform provides the subnets and ACM ARNs as `terraform-values.yaml` files, that are fed into argo deployments.

So we get the best of both worlds, leave tf dealing with static infra, and argo deal with helmisms

**Comment by askulkarni2** [comment]
>So we get the best of both worlds, leave tf dealing with static infra, and argo deal with helmisms

This is the way (unless you know better :))
