### ISSUE TITLE
Kyverno Addon

### ISSUE THREAD

**Issue by Aym3nTN** [aws-ia/terraform-aws-eks-blueprints-addons#282]
Hey community 👋 

Are there any plan to add [Kyverno addon](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v4.32.1/docs/add-ons/kyverno.md) back in this project? 

I saw an old https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/7 that it was removed alongside other addons. 

I can contribute on putting it back if that's ok.

**Comment by bryantbiggs** [comment]
No plans to re-add at this time, but you still can use this module to deploy the addon using the `helm_releases` argument https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/f039cda83fc0902c398684387d95df9beb0143f6/tests/complete/main.tf#L219-L250 if you wish

**Comment by Aym3nTN** [comment]
It's a good idea using `helm_releases` argument, but can I know the reason behind not adding it back?

**Comment by bryantbiggs** [comment]
There simply are too many projects in the CNCF and beyond for us to support those natively here. More importantly, it doesn't make a lot of sense for us to host addons that are simply wrappers over a helm chart

**Comment by Aym3nTN** [comment]
Make total sense now, thanks!
