### ISSUE TITLE
Why Karpenter helm release repository_password keeps showing up as changes in `terraform plan`

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [aws-ia/terraform-aws-eks-blueprints-addons#284]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here
When applying terraform no matter if there were changes or not it keep showing such changes:
```
  # module.eks-addons.module.eks_blueprints_addons.module.karpenter.helm_release.this[0] will be updated in-place
  ~ resource "helm_release" "this" {
        id                         = "karpenter"
        name                       = "karpenter"
      ~ repository_password        = (sensitive value)
        # (30 unchanged attributes hidden)

        # (6 unchanged blocks hidden)
    }
  ```
#### Additional context

I don't think that it should impact anything but I am using terragrunt

**Comment by bryantbiggs** [comment]
that is down to the use of the public ECR token and passing it into the chart. You can pass that token into the Helm provider but it will need to have a specific provider just for Karpenter. 

Closing for now since this is controlled outside of the module
