### ISSUE TITLE
[FEATURE] Allow `addon_config` variable in `aws-for-fluentbit` module (similar to `fargate-fluentbit` module)

### ISSUE THREAD

**Issue by evairmarinho** [aws-ia/terraform-aws-eks-blueprints-addons#29]
#### Is your feature request related to a problem? Please describe

I need customize `aws-for-fluentbit` addon with some filters.

### **aws-for-fluentbit**

In fluent bit ConfigMap `data`, add:
- fluent-bit.conf          
- container-log.conf 
- dataplane-log.conf
- host-log.conf
- parsers.conf 
- filters.conf
- outputs.conf

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/7064fbba2fccddbfd3119564204a0f20db479965/modules/kubernetes-addons/fargate-fluentbit/main.tf#L15-L26

Its mandatory create `locals` named `config` `default_config`  and a `addon_config` variable.

Similar to:

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/7064fbba2fccddbfd3119564204a0f20db479965/modules/kubernetes-addons/fargate-fluentbit/locals.tf#L6-L41

### **kubernetes-addons**
Create `aws_for_fluentbit_addon_config` variable.

#### Describe alternatives you've considered
Install addon without `terraform-eks-blueprints` module.

**Comment by askulkarni2** [comment]
This is no longer an issue in https://github.com/aws-ia/terraform-aws-eks-blueprints-addons as users can pass any arbitrary configuration through `values.yaml`.
