### ISSUE TITLE
Update Karpenter controller AWS IAM role to allow termination of instances with default Name Tag

### ISSUE THREAD

**Issue by jakeskyaws** [aws-ia/terraform-aws-eks-blueprints-addons#296]
Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request

If you are interested in working on this issue or have submitted a pull request, please leave a comment
What is the outcome that you are trying to reach?

## Description

The Karpenter controller uses an AWS Identity and Access Management (AWS IAM) role to grant the permissions to launch and operate Amazon Elastic Compute Cloud (Amazon EC2) instances in your AWS account. The permissions in main prevent the deletion of instances not tagged with Name including *  karpenter.  *. 

```
kubectl -n karpenter logs -l app.kubernetes.io/name=karpenter --all-containers=true -f
```

```
{"level":"ERROR","time":"2023-11-02T14:09:53.409Z","logger":"controller.node.termination","message":"terminating instances, UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::XXXXXXX:assumed-role/karpenter-XXXX is not authorized to perform: ec2:TerminateInstances on resource: arn:aws:ec2:eu-west-2:XXXXXXXX:instance/i-XXXXXXXXX because no identity-based policy allows the ec2:TerminateInstances action.
```

Describe the solution you would like

A Scoped IAM deletion policy added to

https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/6bd285cdfeffeaee5ddf1ceeefe268074c2a7d64/main.tf#L2721

```
   statement {
    sid    = "AllowScopedDeletion"
    effect = "Allow"

    actions = ["ec2:TerminateInstances"]

    resources = [
      "arn:${local.partition}:ec2:${var.region}:*:instance/*",
    ]

    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/kubernetes.io/cluster/${local.name}"
      values   = ["owned"]
    }

    condition {
      test     = "StringLike"
      variable = "aws:ResourceTag/karpenter.sh/nodepool"
      values   = ["*"]
    }
  }`
```

Describe alternatives you have considered

Editing Tags of EC2NodeClass to have karpenter in name 

Additional context
For more information on the upgrade and migration path, please refer to the [Karpenter documentation](https://karpenter.sh/docs/upgrading/v1beta1-migration/).

**Comment by RobertNorthard** [comment]
Also "settings.${local.karpenter_aws_scope}interruptionQueueName" has been renamed to settings.interruptionQueue so it is not backwards compatible in the addons module. Source: https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/6bd285cdfeffeaee5ddf1ceeefe268074c2a7d64/main.tf#L2748
