### ISSUE TITLE
Karpenter: panic 

### ISSUE THREAD

**Issue by momelod** [aws-ia/terraform-aws-eks-blueprints-addons#299]
## Description

v0.10.0 introduces a new bug. 
Karpter pods error with:
`panic: validating settings, missing field(s): aws.clusterName, aws.clusterName is required`

Reverting the module version to 1.9.0 corrects the error. 

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: `v0.10.0`

- Terraform version:
Terraform v1.4.6
- Provider version(s):
+ provider registry.terraform.io/alekc/kubectl v2.0.3
+ provider registry.terraform.io/hashicorp/aws v5.21.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/helm v2.11.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/hashicorp/vault v3.20.1
## Reproduction Code [Required]

Upgrade the module version string, and run `terraform plan`
Observe the output and note the required values have been incorrectly placed in the yaml hierarchy:

```
      - set {
          - name  = "settings.aws.clusterName" -> null
          - value = "eks02-prod-rops-cac1" -> null
        }
      + set {
          + name  = "settings.clusterName"
          + value = "eks02-prod-rops-cac1"
        } 
```
## Expected behaviour

Values should be in the correct place so Karpenter wont  immediately panic and pods should be in a running state after fresh install.

## Actual behaviour

Karpenter pods fail to start with the error:  `panic: validating settings, missing field(s): aws.clusterName, aws.clusterName is required`

## Additional context

I confirmed this problem on both existing and freshly installed clusters.

**Comment by bryantbiggs** [comment]
please try using `v1.11.0` which was recently released - more details can be found here https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/298

**Comment by momelod** [comment]
After upgrading to v1.11.0 I see a new error: `panic: failed to setup nodeclaim provider id indexer: failed to get API group resources: unable to retrieve the complete list of server APIs: karpenter.sh/v1beta1: the server could not find the
requested resource`

So after that I re-installed karpenter by setting `enable_karpenter = false`, followed by `terraform apply`. After removal, went back in set `enable_karpenter = true` and once more `terraform apply`. 

This recreated everything correctly and my Karpenter pods are now ready.

Thank you very much

**Comment by momelod** [comment]
Upon creating a new node, I am getting more errors. This time in reference to the default launch template which seems undefined by the module.

`"error": "launching machine, creating instance, getting launch template configs, getting launch templates, neither spec.provider.instanceProfile nor --aws-default-instance-profile is specified"`

I see this value was set prior to v1.10.0 but is not set in this version.

terraform plan:
```
- set {
          - name  = "settings.aws.defaultInstanceProfile" -> null
          - value = "karpenter-my-superawesomecluser-20231104170235461500000001" -> null
        }
```

**Comment by bryantbiggs** [comment]
Have you seen the Karpenter upgrade guide https://karpenter.sh/preview/upgrading/upgrade-guide/ - and specifically, for 0.32.0?

**Comment by momelod** [comment]
Sadly, no.  I didn't see a breaking change in the release notes so was not aware I had to.  I foolishly assumed it would work out of the box.
