### ISSUE TITLE
Karpenter: Add CNI policy for IPv6 cluster

### ISSUE THREAD

**Issue by vkaylee** [aws-ia/terraform-aws-eks-blueprints-addons#301]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Currently, I see the karpenter role does not support `AmazonEKS_CNI_IPv6_Policy` policy.
Check here: https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/v1.11.0/main.tf#L2964

the karpenter node does not have right to issue an ipv6 for pod.

This policy is created in the eks module.
we should have an output to be able to enable it in karpenter role automatically if the cluster is IPv6 stack.

#### Describe the solution you would like

I have a suggestion to change the line to
```terraform
AmazonEKS_CNI_Policy               = try(var.karpenter_node.enable_cni_ipv6_policy, false) ? "arn:${local.partition}:iam::${local.account_id}:policy/AmazonEKS_CNI_IPv6_Policy" : "${local.iam_role_policy_prefix}/AmazonEKS_CNI_Policy",
```
We can input:
```terraform
karpenter_node = {
  enable_cni_ipv6_policy = true
}
```

#### Describe alternatives you have considered

EKS module can export a final `CNI policy arn` that is used by the node role.
Attach that `CNI policy arn` to the karpenter role in `terraform-aws-eks-blueprints-addons `

**Comment by vkaylee** [comment]
I have just realized that we can attach CNI policy based on the EKS cluster IP address family info. #303

**Comment by bryantbiggs** [comment]
this policy technically does not exist unless its created from the EKS module. For now, users can create the policy, either on their own or from the EKS module, and then pass that into the karpenter through https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/1b081736b7ef10626a19be20998ead8f6032262a/main.tf#L2972C51-L2972C79

**Comment by bryantbiggs** [comment]
after consideration, we do not want to duplicate the policy creation here - users should pass in any additional permissions/policies as needed. For IPv6 this is somewhat different because there currently isn't a managed policy for this but one can be created by the EKS module, or users can create their own, and then pass it into the addon here
