### ISSUE TITLE
new (but old) addon: Kubernetes Dashboard

### ISSUE THREAD

**Issue by LeoSpyke** [aws-ia/terraform-aws-eks-blueprints-addons#308]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
Since it is not clear what do you mean with "we have made a decision to only support the provisioning of a _**certain**_ core set of add-ons" in [this documentation section](https://aws-ia.github.io/terraform-aws-eks-blueprints-addons/main/helm-release/#helm-release-add-ons), I'm here to ask if you plan to re-add the support for the Kubernetes Dashboard install through Helm Chart.
The plugin [was available in v4.32.1](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/v4.32.1/modules/kubernetes-addons/kubernetes-dashboard).

#### Describe the solution you would like
It would be awesome to have the same logic as other addons.

#### Describe alternatives you have considered
I'm not aware of other non vendor locking dashboards, but I'm open to suggestions.

**Comment by bryantbiggs** [comment]
There are no plans currently to re-add this. However, you can easily deploy the dashboard using this module or simply use a standalone `helm_release` resource. Here is an example of deploying any Helm chart with this module https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/1b081736b7ef10626a19be20998ead8f6032262a/tests/complete/main.tf#L220-L235

**Comment by boatmisser** [comment]
Thats useful, I wasn't really aware of that module, thanks.
Is there an example of a `helm_release` with a ServiceAccount and an IAM Role?

**Comment by LeoSpyke** [comment]
> Thats useful, I wasn't really aware of that module, thanks. Is there an example of a `helm_releases` with a ServiceAccount and an IAM Role?

I think that for this use case you could make use of [terraform-aws-eks-blueprints-addon](https://github.com/aws-ia/terraform-aws-eks-blueprints-addon/tree/main) (without the final "s"). Is that right @bryantbiggs?

**Comment by bryantbiggs** [comment]
@LeoSpyke correct! The singular form is just for creating a single addon - and it can provide IRSA support if required by the addon. The plural form is a collection of addons, with most being implemented using the singular form module

For now, I am going to close this issue but happy to take any further questions
