### ISSUE TITLE
Make the default `set` logic overridable so that I can replace every value.

### ISSUE THREAD

**Issue by boatmisser** [aws-ia/terraform-aws-eks-blueprints-addons#311]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

When using a helm based addon e.g. `cluster_autoscaler` I want to be able to override every value myself so that I do not get any of the default values set in the blueprint.

#### Describe the solution you would like

The most flexible solution I can think of is to replace the default `set` with my `set` (including empty if I want) instead of adding to it; which appears to be the current functionality.
Then, to keep the ability to extend the default `set` a new variable could be added `extra_set` or some such; which behaves the same way it does now.
Thereby allowing me to set every variable myself while keeping all the other benefits of the blueprint.

#### Describe alternatives you have considered

1. Ability to disable the `set` instead; leaving only `values` as a method of passing arguments to helm.
2. Similar to my preferred solution, but reversed; I.e. leave all the current `set` logic alone and a new `set_override` variable that replaces it.

#### Additional context

N/A

**Comment by bryantbiggs** [comment]
> When using a helm based addon e.g. cluster_autoscaler I want to be able to override every value myself so that I do not get any of the default values set in the blueprint.

Unfortunately, I think this conflicts with the premise of the project. What values are you wanting to set on cluster-autoscaler that differ from the minimal defaults we are providing today?

**Comment by boatmisser** [comment]
Thats was just an example; in `cluster-autoscaler` its the image tag.
The blueprint automatically selects the latest image tag, but we have restrictions on this; we can only pull from our private repo; to which we have to copy pubic images.
In this case if blueprint is updated to 1.28.1 and we have not yet copied that into our repo then an apply of the Terraform will deploy a broken deployment.

Another one is around `velero` where I cannot set my own prefix; I raised this separately in #307 before I had issues with another template.

I do not see how the ability to overrider default helm values conflicts with the project, there are plenty of values that we can override, it just happens that when some of them are applied a certain way (via the `set` operation) we cannot.
Thanks
