### ISSUE TITLE
karpenter helm_release respository_password needs to be ignored as change

### ISSUE THREAD

**Issue by cdenneen** [aws-ia/terraform-aws-eks-blueprints-addons#313]
Currently everytime you `plan` or `apply` to provision karpenter through this module it does another helm release even if nothing changes due to the ECR password lookup.

This needs to be accounted for and ignored to avoid a change for every apply:

```
  # module.k8s-cluster.module.eks_blueprints_addons[0].module.karpenter.helm_release.this[0] will be updated in-place
  ~ resource "helm_release" "this" {
        id                         = "karpenter"
        name                       = "karpenter"
      ~ repository_password        = (sensitive value)
        # (30 unchanged attributes hidden)

        # (8 unchanged blocks hidden)
    }
```

I believe there is a way for the `lifecycle {}` to ignore these with something like:

```hcl
lifecycle {
  ignore_changes = [
    repository_password
  ]
}
```

**Comment by FernandoMiguel** [comment]
if you ignore that, then the password isnt updated, and then you fail to pull from the repo

**Comment by cdenneen** [comment]
The password changing doesn’t affect the rest of the values. If the chart version or parameters change then it will update. The ignore only affects if the password alone changes(which is every run) but nothing else.

**Comment by andyli** [comment]
It seems we can left out `repository_username` and `repository_password` to use unauthenticated pull, according to
https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#4-install-karpenter

I tried it after doing `helm registry logout public.ecr.aws`, terraform successfully installed the karpenter chart without setting `repository_username` and `repository_password`.
