### ISSUE TITLE
is the aws-ebs-csi-driver automatically associated with an IRSA account?

### ISSUE THREAD

**Issue by vstthomas** [aws-ia/terraform-aws-eks-blueprints-addons#327]
# When enabling the `aws-ebs-csi-driver` in blueprints, is it automatically associated with an IRSA account?

```hcl
module "eks_blueprints_addons" {
  source  = "aws-ia/eks-blueprints-addons/aws"
  version = "~> 1.12.0"

  eks_addons = {
    aws-ebs-csi-driver = {
      most_recent = true
    }
...
  }
}
```

This addons method only seems to inherit from the node, yes?

```hcl
# module.eks_blueprints_addons.aws_eks_addon.this["aws-ebs-csi-driver"]:
resource "aws_eks_addon" "this" {
    addon_name                  = "aws-ebs-csi-driver"
    addon_version               = "v1.25.0-eksbuild.1"
    arn                         = "arn:aws:eks:us-east-1:367652197469:addon/gitops-demo-stage/aws-ebs-csi-driver/2ac61ace-9b13-a344-4514-b7de811f4d95"
    cluster_name                = "gitops-demo-stage"
...
}
```

All of the docs point to associating it with an IRSA; examples:
https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html
https://repost.aws/knowledge-center/eks-persistent-storage

**Comment by bryantbiggs** [comment]
no - you need to create [the role](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/0e9d6c9b7115ecf0404c377c9c2529bffa56d10d/tests/complete/main.tf#L323-L339) and then pass it to the addon https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/0e9d6c9b7115ecf0404c377c9c2529bffa56d10d/tests/complete/main.tf#L111

**Comment by vstthomas** [comment]
Brilliant, that worked. Thank you
