### ISSUE TITLE
[ FEATURE ] Make cert-manager CA endpoint configurable & add Certificate resource for ACME's chart.

### ISSUE THREAD

**Issue by hakmkoyan** [aws-ia/terraform-aws-eks-blueprints-addons#33]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

cert-manager module's ACME CA's endpoint is not configurable, though there are many other ACME Certificate Authority servers (such as ZeroSSL and other acme servers) that can replace Let's Encrypt, in the module's custom chart (both in clusterissuer-production.yaml and clusterissuer-staging.yaml) it is hard-coded to lets-encrypt's endpoint. Also if the module deploys custom chart for lets-encrypt, it only deploys the ClusterIssuer manifest, in my conviction there (in cert-manager's lets-encrypt custom chart's folder) should also be a cert-manager custom resource called 'Certificate', which will be referenced to deployed ClusterIssuer and after deploy will generate certificate.

#### Describe the solution you would like

The solution I would like is to add cert-manager's custom resource Certificate in the same chart with ClusterIssuer resource, and make ACME endpoint configurable, notice that some ACME servers require keyID and Secret for connection, which means that external account binding should also be used in ClusterIssuer's manifest.

#### Additional context

I already made that solution possible and can create a PR if this issue gets approved.

**Comment by bryantbiggs** [comment]
Thanks for raising the issue @hakmkoyan! After reviewing with the team, the approach that we will look at implementing is to make the `cert-manager` addon more generic across the different certificate authority providers. Instead of providing native support for LetsEncrypt/etc., we will look at making the `spec.acme` attribute configurable, allowing users to pass in the values that suits their issuer. We can look to add an example that demonstrates how to pass different CA issuers to the addon for vending certificates (i.e. - LetsEncrypt)

If you are interested in making this change, please feel free to open a PR, otherwise we will add this to our backlog

**Comment by hakmkoyan** [comment]
@bryantbiggs, review this repository created by me. If it works for you I can implement the same for your blueprints, review so that I don't lose time creating PR in case you do not want it.

**Comment by bryantbiggs** [comment]
Thank you for sharing - however, I don't think the solution we provide here will get that involved with CRs, etc. I'll take a look today and see what changes might be possible

**Comment by hakmkoyan** [comment]
I researched for a long time, and did not find a chart that really deploys certificate and cluster issuer, so official chart for that sitll not exist. By saying "implement the same for your blueprints" I mean, to create he charts and terraform codebase for your repo, I did not mean refering to my repo from your terraform codes. Thanks for fast response.
