### ISSUE TITLE
Adding support for the default namespace service account to access AWS Secret Manager in external-secrets.

### ISSUE THREAD

**Issue by vilakshan2996** [aws-ia/terraform-aws-eks-blueprints-addons#337]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Currently, the service account for external-secrets is created in the external-secrets namespace when using the Helm chart. However, my applications are in the default namespace, and I want the external-secrets service account to be in the default namespace as well. This allows me to update the Kubernetes Secret in the default namespace, and subsequently, utilize those updated values in my applications. If the external-secrets service account is in a different namespace, I cannot use the secret store in the default namespace to fetch updates from AWS Secret Manager. Please correct me if I am mistaken.

#### Describe the solution you would like

So, it would be better if we could modify the namespace of the oidc_providers service account to a custom namespace that the user can specify when using external_secrets. This way, the SecretStore can utilize that service account to access AWS Secret Manager.

**Comment by rodrigobersa** [comment]
Hey @vilakshan2996, thanks for raising this.

You mean to have the SA deployed in a namespace different from the Helm Chart? If yes, have you tested this or have any examples of this working in your environment? Asking because IRSA may not have permissions if deployed like this.

**Comment by rodrigobersa** [comment]
Hey @vilakshan2996.

So you're creating the SA outside the `addons` module? And external-secrets could successfully access the AWS Resources?

**Comment by vilakshan2996** [comment]
Yes

**Comment by bryantbiggs** [comment]
What is the end goal you are trying to achieve? In theory, this module provides everything needed with options to customize but its not clear what your overall end goal or motivation is

**Comment by vilakshan2996** [comment]
The service account in the default namespace utilizes an OIDC identity provider for connecting to AWS Secret Manager. Currently, only the service account in the 'external-secret' namespace is permitted to access the Secret Manager.

Final goal is to access secret for my application on default namespace.

**Comment by bryantbiggs** [comment]
Ok, and the following doesn't work?

```hcl
module "eks_blueprints_addons" {
 ...

  enable_external_secrets = true
  external_secrets = {
    create_namespace = false
    namespace        = "default"
  }
}

**Comment by vilakshan2996** [comment]
In our scenario, we deploy our primary components (applications) within the default namespace, utilizing Fargate. Meanwhile, additional addon applications, such as external-secret , coredns in others namespaces, run on an EKS managed node group. External-secret generates three pods, and the cost associated with running it on Fargate is higher compared to hosting it on an EKS managed EC2 instance.

**Comment by bryantbiggs** [comment]
I'm sorry but I don't follow how that is related. Did you try plugging the above configuration snippet into your configuration?
