### ISSUE TITLE
Unsupported attribute: eks_blueprints_addons/main.tf line 3688

### ISSUE THREAD

**Issue by Lock128** [aws-ia/terraform-aws-eks-blueprints-addons#354]
Since the merge of the last PR this line is giving an error:
https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/commit/b338f77384a79ff01dfba5fba4477533afe8fe51#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR3688

```
╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/eks_blueprints_addons/main.tf line 3688, in locals:
│ 3688:   wait_for_cert_manager = var.cert_manager.wait ? [module.cert_manager] : []
│     ├────────────────
│     │ var.cert_manager is object with no attributes
│ 
│ This object does not have an attribute named "wait".```

**Comment by metroidprototype** [comment]
Can add this to your module args until a fix is merged
```
cert_manager = {
  wait = false
}
```

**Comment by Lock128** [comment]
In my case that doesn't work as I am using this module as a transient dependency of [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks) (well  to be honest - I don't know how to pass module args there, even tho it might be technically possilbe....)
