### ISSUE TITLE
cert-manager CRD's not installed after apply 

### ISSUE THREAD

**Issue by JamesCalleja** [aws-ia/terraform-aws-eks-blueprints-addons#356]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:
Terraform v1.7.1
- Provider version(s):
module "eks_blueprints_addons" {
  source  = "aws-ia/eks-blueprints-addons/aws"
  version = "1.13.0"

## Reproduction Code [Required]

module "eks_blueprints_addons" {
  source  = "aws-ia/eks-blueprints-addons/aws"
  version = "1.13.0"

  cluster_name      = data.terraform_remote_state.source_state.outputs.cluster_name
  cluster_endpoint  = data.terraform_remote_state.source_state.outputs.cluster_endpoint
  cluster_version   = data.terraform_remote_state.source_state.outputs.cluster_version
  oidc_provider_arn = data.terraform_remote_state.source_state.outputs.oidc_provider_arn

  eks_addons = {
    aws-ebs-csi-driver = {
      most_recent = true
    }
    coredns = {
      most_recent = true
    }
    vpc-cni = {
      most_recent = true
    }
    kube-proxy = {
      most_recent = true
    }
  }

  # K8s Add-ons
  enable_aws_for_fluentbit              = true
  enable_aws_cloudwatch_metrics         = true
  enable_cert_manager                   = true
  cert_manager_route53_hosted_zone_arns = ["arn:aws:route53:::hostedzone/Z03882443UC11ZSXYMSGG"]
  enable_external_secrets               = true
  enable_aws_load_balancer_controller   = true
  enable_karpenter                      = true
}

create a vanilla EKS cluster if first apply run. Second apply to configure EKS addons such as above. 

## Expected behaviour

Addons and crd are installed and ready to use. 

## Actual behaviour

the second apply works, cert-manager names space, pods, and helm chart are there, but no issuer or cluster issuer is created. 

### Terminal Output Screenshot(s)

module.eks_blueprints_addons.module.cert_manager.helm_release.this[0]: Still creating... [10s elapsed]
module.eks_blueprints_addons.module.cert_manager.helm_release.this[0]: Still creating... [20s elapsed]
module.eks_blueprints_addons.module.cert_manager.helm_release.this[0]: Creation complete after 25s [id=cert-manager]

## Additional context

I can find no clear error as to what's going wrong. 

The previous blue prints module I have been using did a complete working set up of cert-manager hence my expectations that this one would do the same with cert-manager = True.

 source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.32.1"

any help would be appreciated.

**Comment by askulkarni2** [comment]
I am not seeing this upon a fresh install using the latest release. Can you give it another go with `v1.15.1`?

**Comment by JamesCalleja** [comment]
Hi @askularni2

Yep using v1.15.1 seems to resolve that behaviour. All CRD's and issuers etc are there as expected. 

Thanks very much
