### ISSUE TITLE
Enable AWS Managed Prometheus

### ISSUE THREAD

**Issue by Plork** [aws-ia/terraform-aws-eks-blueprints-addons#363]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Describe the solution you would like

When adding kube-prometheus-stack all it does at the moment is the helm install. I would like an option to enable the aws managed prometheus via the gitops control plane.

as shown here:
https://github.com/terraform-aws-modules/terraform-aws-iam/blob/v5.34.0/examples/iam-role-for-service-accounts-eks/main.tf#L273

add the following iam statement to the blueprint module.

**Comment by bryantbiggs** [comment]
I'm sorry, I don't quite follow - you want this module to create the IAM role for AMP?

**Comment by Plork** [comment]
Yeah sorry if it wasn't clear enough ;)

I would like to enable IRSA for AWS Managed Prometheus.
https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-ingest-metrics-new-Prometheus.html

**Comment by Plork** [comment]
I can work on a PR, just wanted to see what needs to be done for this.

**Comment by bryantbiggs** [comment]
so  if you are following the GitOps methodology to deploy charts, you're really just looking for the IAM role, correct? Any reason you can't use the IAM role that you linked?

**Comment by Plork** [comment]
we could but we wanted to use the gitops bridge method for deploying with argo and wanted to keep everything in one place

**Comment by bryantbiggs** [comment]
@csantanapr do you have input on the above thread?

**Comment by allamand** [comment]
@Plork , you can use GitOps-bridge to set the iam role you want to prometheus in the secret, you can found an example here https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/patterns/blue-green-upgrade/modules/eks_cluster/main.tf#L89 then ArgoCD can use this secret in the values to deploy you addon with appropriate iam role
