### ISSUE TITLE
Upgrade to latest aws-load-balancer-controller helm chart

### ISSUE THREAD

**Issue by rgl** [aws-ia/terraform-aws-eks-blueprints-addons#368]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Use the [latest aws-load-balancer-controller helm chart version](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases).

At the time of creating this issue, this repository installs 1.4.8 and the latest version is 1.7.1.

#### Describe the solution you would like

Install an upgraded [aws-load-balancer-controller helm chart version](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases) version.

#### Describe alternatives you have considered

None.

#### Additional context

None.

**Comment by bryantbiggs** [comment]
hello! the default chart version is currently 1.7.1 https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/f28ce287d944743f885537f9663571741063780d/main.tf#L1419

**Comment by rgl** [comment]
@bryantbiggs oh, I'm so sorry... I've mistakenly used https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/releases/tag/v1.1.1 instead of https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/releases/tag/v1.16.0. sorry for wasting your time, and thanks for pointing this out!

**Comment by bryantbiggs** [comment]
no worries at all, thats what we're here for!
