### ISSUE TITLE
Profile Fargate SPOT

### ISSUE THREAD

**Issue by hugobritobh** [aws-ia/terraform-aws-eks-blueprints-addons#374]
- [X] ✋ I have searched the open/closed issues and my issue is not listed.

I'm using EKS 1.29 and all plugins in the latest versions.

I would like to know how do I use the "Fargate Profile", but determine that it uses SPOT.
For example, I want to use Karpenter and CoreDNS on Fargate with capacityProvider : FARGATE_SPOT

I'm not saying this is an ideal scenario for productive environments, but I would like to know if this option exists.

#### Provide a link to the example/module related to the question

[FargateProfile](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/fargate_profile/main.tf)

[Karpenter](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/karpenter/main.tf)

**Comment by bryantbiggs** [comment]
https://github.com/aws/containers-roadmap/issues/622

**Comment by bryantbiggs** [comment]
you can follow along on that issue for EKS Fargate spot support - for now though, its not supported
