### ISSUE TITLE
Adding support role_permissions_boundary_arn for AWS Load Balancer Controller

### ISSUE THREAD

**Issue by vietwow** [aws-ia/terraform-aws-eks-blueprints-addons#379]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

As we are using this module to create AWS Load Balancer Controller in the production environment, so there is a security restriction for creating new IAM roles that require we have to input our predefined IAM permissions boundary

Code I used :
```
module "eks_kubernetes_addons" {
  source  = "aws-ia/eks-blueprints-addons/aws"
  version = "1.16.2"

  cluster_name      = module.eks.cluster_name
  cluster_endpoint  = module.eks.cluster_endpoint
  cluster_version   = module.eks.cluster_version
  oidc_provider_arn = module.eks.oidc_provider_arn

  enable_aws_load_balancer_controller = true
  aws_load_balancer_controller = {
    create_namespace = true
    namespace        = "lb-controller"
    values = [jsonencode(yamldecode(<<-EOT
      clusterName: ${var.cluster_name}
    EOT
    ))]
  }
}
```

And the error I got :
> module.eks-cluster.module.eks_kubernetes_addons.module.aws_load_balancer_controller.aws_iam_role.this[0]: Creating...
module.eks-cluster.module.eks_kubernetes_addons.module.aws_load_balancer_controller.aws_iam_policy.this[0]: Creating...
module.eks-cluster.module.eks_kubernetes_addons.module.aws_load_balancer_controller.aws_iam_policy.this[0]: Creation complete after 1s [id=arn:aws:iam::753868314987:policy/alb-controller-20240325234138260200000002]
╷
│ Error: creating IAM Role (alb-controller-20240325234138260000000001): AccessDenied: User: arn:aws:sts::xxxxxxxx:assumed-role/default_deployer_role/builder_session is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::xxxxxxxx:role/alb-controller-20240325234138260000000001 because no permissions boundary allows the iam:CreateRole action
│ 	status code: 403, request id: 4fbbd4f0-8eac-47aa-ae7a-85129158db90
│
│   with module.eks-cluster.module.eks_kubernetes_addons.module.aws_load_balancer_controller.aws_iam_role.this[0],
│   on .terraform/modules/eks-cluster.eks_kubernetes_addons.aws_load_balancer_controller/main.tf line 160, in resource "aws_iam_role" "this":
│  160: resource "aws_iam_role" "this" {
│
╵

#### Describe the solution you would like

Add an variable like "role_permissions_boundary_arn" to for AWS Load Balancer Controller

**Comment by bryantbiggs** [comment]
its already there, no? https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/089e81a3778fd7ebeda00fed0c26259347028a2c/main.tf#L1470

**Comment by vietwow** [comment]
> its already there, no?
> 
> https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/089e81a3778fd7ebeda00fed0c26259347028a2c/main.tf#L1470

Hi @bryantbiggs , thank you for your quick response.
