### ISSUE TITLE
[FEATURE] Additional helm values for kubernetes-addons which won't delete the default

### ISSUE THREAD

**Issue by dex4er** [aws-ia/terraform-aws-eks-blueprints-addons#38]
#### Is your feature request related to a problem? Please describe
I can't just add additional values for helm. I have to replace the default valyes.yaml with full copy of all values.

Ie.

```terraform
module "aws_eks_addons" {
  external_dns_helm_config = {
    values = [yamlencode({
      sources : ["service", "istio-gateway"]
    })]
  }
}
```

will remove settings from the default values.yaml like provider, zoneIdFilters and aws.region.

#### Describe the solution you'd like

I would like to see such pattern (example for externa-dns):

```terraform
variable "helm_values" {
  type        = any
  default     = {}
  description = "Additional Helm values"
}

locals {
  default_helm_config = {
    values      = [local.default_helm_values, var.helm_values]
  }
  default_helm_values = templatefile("${path.module}/values.yaml", {
    aws_region      = var.addon_context.aws_region_name
    zone_filter_ids = local.zone_filter_ids
  })
}
```

Then:

```terraform
module "aws_eks_addons" {
  external_dns_helm_values = yamlencode({
    sources : ["service", "istio-gateway"]
  )}
}
```

The pattern uses ability of Helm which merges 2 or more values.yaml files.

**Comment by bryantbiggs** [comment]
closing this out with the current implementation provided by the new addons module. please feel free to open any new issues or feature requests if there are any gaps - thank you!
