### ISSUE TITLE
Question about tag: v1.12.0

### ISSUE THREAD

**Issue by carlosj934** [aws-ia/terraform-aws-eks-blueprints-addons#388]
### Discussed in https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/discussions/385

<div type='discussions-op-text'>

<sup>Originally posted by **carlosj934** April  5, 2024</sup>
Hello, I was curious if anyone could point out which commit hash is associated to version = "~> 1.12". It looks like when trying to use this version, tag: v1.16.0 aligns closer to the version rather than tag: v1.12.0. Thank you! @askulkarni2  </div>

**Comment by carlosj934** [comment]
@bryantbiggs

**Comment by bryantbiggs** [comment]
Hi - I don't quite follow, what exactly are you trying to do? 

For ref, here is a diff between 1.12 and 1.16 https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/compare/v1.12.0...v1.16.0

**Comment by carlosj934** [comment]
> Hi - I don't quite follow, what exactly are you trying to do?
> 
> For ref, here is a diff between 1.12 and 1.16 [v1.12.0...v1.16.0](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/compare/v1.12.0...v1.16.0)

Hello,
I have a local version of this repo that I'm sourcing for my personal project. When I source it directly from the terraform registry I would point it at version ~>1.12 but when trying change my source to be pointing at the locally hosted version of this module it seems like tag v1.16.0 keeps my environment the same but tag v1.12.0 is rolling back the versions of alb controller helm release and making a change the IAM policy of the alb controller. So I was just curious if there was a difference between the version numbers on the terraform registry compared to the tag numbers on github. Thank you! @bryantbiggs
