### ISSUE TITLE
fargate_fluentbit_cw_log_group retention incorrectly documented

### ISSUE THREAD

**Issue by pricealexandra** [aws-ia/terraform-aws-eks-blueprints-addons#392]
## Description

In the docs [here](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/7755fb6ec97139d34b7d01467ce7f20164cbd24a/docs/addons/fargate-fluentbit.md) it shows `retention_in_days` for the `fargate_fluentbit_cw_log_group` configuration. It seems like in the code it's expected to be just `retention` instead, and that was the only way we got the configuration to work.

Is it intended to be `retention` or `retention_in_days`? We'd be happy to open a PR to correct either the documentation or the code, depending on what the answer is.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: ~> 1.16

Terraform v1.8.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.47.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.4
+ provider registry.terraform.io/hashicorp/helm v2.13.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.29.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/time v0.11.1
+ provider registry.terraform.io/hashicorp/tls v4.0.5

## Reproduction Code [Required]

Works:
```
  fargate_fluentbit_cw_log_group = {
    retention = 7
  }
```
Does not work, but is documented:
```
  fargate_fluentbit_cw_log_group = {
    retention_in_days = 7
  }
```

see code above. reproduce issue by applying.

## Expected behaviour
Either the docs say just `retention` which works, or the code is updated to use `retention_in_days` to match the documentation.

## Actual behaviour
The documented retention feature does not work because it has the wrong name.

**Comment by danielthieleog** [comment]
I prefer to adapt the documentation so as not to break existing code.
Similar to "Fargate FluentBit" the documentation for "AWS for Fluent Bit" already contains `retention`.

**Comment by pricealexandra** [comment]
Sorry for the delay, I was out of town but I should be able to open a PR to update the docs this week. Thanks for the direction @danielthieleog
