### ISSUE TITLE
Add the create_policy variable to allow users attach their own policy

### ISSUE THREAD

**Issue by markoskandylis** [aws-ia/terraform-aws-eks-blueprints-addons#394]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

I want to have the ability to attach my own policy on the addons without having to create the default one, this is an existing faction of the addon module.

#### Describe the solution you would like

adding the variable create_policy to the modules addons

**Comment by bryantbiggs** [comment]
one of the main intents of this module is to make it easy to deploy commonly used addons. what is the benefit here if the policy is not created - then its simply an IAM role and a helm release resource

**Comment by markoskandylis** [comment]
hi Bryan, the idea would be that use user can create their own more fine grained policy that they want to attach to the sa role. You can already disable the create of the default role its just an enchantment in case the use wants to keep the role but just go in more detail about the policy that they will use for this role :)

**Comment by bryantbiggs** [comment]
I think at that point, you are better off creating your own role and helm release

**Comment by markoskandylis** [comment]
I will message you internally as well to explain more in detail the reason of the pull request :)

**Comment by bryantbiggs** [comment]
if they want to continue on this route, they can roll their own version of this module (i.e. - fork it), or they can leverage the underlying module we use https://github.com/aws-ia/terraform-aws-eks-blueprints-addon and pass in their own values

Closing this out for now
