### ISSUE TITLE
Is there a reason AWS Gateway API Controller has unbounded IAM permission to vpc-lattice?

### ISSUE THREAD

**Issue by cls-aws** [aws-ia/terraform-aws-eks-blueprints-addons#401]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

The AWS Gateway API Controller has vpc-lattice:* permission which gives it the ability to modify lattice control plane and configurations outside of this solution. Can it be scoped down?

https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/main/main.tf#L3583

It can also create any IAM service-linked role it wants but this is less of a risk than the vpc-lattice permissions.
https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/main/main.tf#L3584

**Comment by bryantbiggs** [comment]
It matches what the gateway controller policy recommends https://github.com/aws/aws-application-networking-k8s/blob/15d0899bb4ccaf4327ab3cac68d058d7d159b39e/config/iam/recommended-inline-policy.json#L7
