### ISSUE TITLE
Velero AWS plugin version is haedcoded

### ISSUE THREAD

**Issue by sandeep6678** [aws-ia/terraform-aws-eks-blueprints-addons#403]
## Description

This is hardcoded in the main.tf -

   - name: velero-plugin-for-aws
     image: velero/velero-plugin-for-aws:v1.7.1
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - mountPath: /target
         name: plugins

I Am not able to upgrade the latest version to v1.10.0.

Please let me know how do I fix this ?
Can we make this module upgraded for latest velero version ?

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by askulkarni2** [comment]
You can override the helm version or any attributes of the helm chart as shown in the docs [here](https://aws-ia.github.io/terraform-aws-eks-blueprints-addons/main/addons/velero/).
