### ISSUE TITLE
When use aws_for_fluentbit disable create cloudwatch log group, will let fluentbit config setting LogGroupName to ""

### ISSUE THREAD

**Issue by neilkuan** [aws-ia/terraform-aws-eks-blueprints-addons#408]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: `v1.16.2`

- Terraform version: `v1.9.5`

- Provider version(s): 
```bash
Terraform v1.9.5
on darwin_arm64
+ provider registry.terraform.io/alekc/kubectl v2.0.4
+ provider registry.terraform.io/hashicorp/aws v5.61.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.4
+ provider registry.terraform.io/hashicorp/helm v2.15.0
+ provider registry.terraform.io/hashicorp/http v3.4.4
+ provider registry.terraform.io/hashicorp/kubernetes v2.27.0
+ provider registry.terraform.io/hashicorp/local v2.5.1
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.2
+ provider registry.terraform.io/hashicorp/time v0.12.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5
+ provider registry.terraform.io/rancher/rancher2 v4.1.0
```

## Reproduction Code [Required]

```hcl
module "eks_blueprints_addon" {
  ...
  source  = "aws-ia/eks-blueprints-addons/aws"
  version = "1.16.2"
  ...
  enable_aws_for_fluentbit = true
  aws_for_fluentbit_cw_log_group = {
    create = false
    name   = local.cb_log_group_name
  }
  aws_for_fluentbit = {
    create_namespace = false
    namespace        = var.namespace
    chart_version    = "0.1.26"
    wait                    = false
    timeout              = 600
    values = [
      <<-EOT
      cloudWatchLogs:
        autoCreateGroup: false
        endpoint: https://logs.${var.region}.amazonaws.com.
        region: ${var.region}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                - fargate
    EOT
    ]
  }
}
```

## Expected  behaviour

Define Good format like that pic.
![image](https://github.com/user-attachments/assets/371b5910-e676-4053-a262-64aafe0e266a)

## Actual behaviour

Because this [condition](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/089e81a3778fd7ebeda00fed0c26259347028a2c/main.tf#L570) let `local.aws_for_fluentbit_cw_log_group_name` define to `""` to let configmap `aws-for-fluent-bit` to wrong format. 

![image](https://github.com/user-attachments/assets/459c998f-eee0-4d60-b551-efd26c6f884b)

**Comment by bryantbiggs** [comment]
You haven't shared what value you are actually using - we can't see what your variable is

```hcl
aws_for_fluentbit_cw_log_group = {
    create = false
    name   = local.cb_log_group_name # what is this value?
  }
```

**Comment by neilkuan** [comment]
local.cb_log_group_name 
can been "eks-log-group". (It can be any value but not "".

**Comment by neilkuan** [comment]
> Why do you not want Terraform to create the log group?

In our company, we use Karpenter to create machines. Karpenter runs on Fargate, and the logic for creating a new EKS Cluster is to create the EKS Cluster first, followed by creating a Fargate Profile for CoreDNS and Karpenter. We've configured Fargate to send logs to a LogGroup, so the LogGroup should be created first. However, in our current setup, the aws_for_fluentbit addon module depends on the completion of the Karpenter Helm install, meaning that the LogGroup won't be created until after Karpenter is installed.

We want to record Karpenter's logs to the specified LogGroup from the beginning (which was originally created by aws_for_fluentbit). Therefore, we need to pre-create the LogGroup so that the applications running on Fargate, as well as aws_for_fluentbit, can send logs to the pre-created LogGroup.
