### ISSUE TITLE
LBC Pod Startup Issues in EKS 1.30 Deployment

### ISSUE THREAD

**Issue by gurusing-rakbank** [aws-ia/terraform-aws-eks-blueprints-addons#413]
- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

I deployed EKS version 1.30 along with all the necessary add-ons. However, the LBC pods initially failed to start. After manually adding the VPC ID and region to the deployment, the pods began running successfully.

**Comment by askulkarni2** [comment]
can you share your code?
