### ISSUE TITLE
Support event bridge prefixes for Karpenter

### ISSUE THREAD

**Issue by svennam92** [aws-ia/terraform-aws-eks-blueprints-addons#417]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

We need a way to define a prefix for Karpenter event bridge rules so we can configure more secure IAM roles. It looks like we had this support in the past but it is no longer configurable.

See here: https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/5a91f14589d27f235c3ee8bb85b3871d9efce53e/main.tf#L2932

This was previously supported through [`rule_name_prefix`](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/7f7f0babada704d2b80188dc76b5fa2f737bed1f/modules/karpenter/README.md#input_rule_name_prefix) implemented in https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/11

#### Describe the solution you would like

Support a variable that allows us to configure this prefix. Same solution as was previously implemented: https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/11

**Comment by askulkarni2** [comment]
> so we can configure more secure IAM roles
I think I am missing something. What do you mean by this?
