### ISSUE TITLE
CloudWatch Observability addon

### ISSUE THREAD

**Issue by DesAWSume** [aws-ia/terraform-aws-eks-blueprints-addons#428]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

In the managed add-on, there is a Amazon CloudWatch Observability. 
It extends more with the `enable_aws_cloudwatch_metrics` and `enable_aws_for_fluentbit` combined, 

Can this be made into this module? 

#### Describe the solution you would like

N/A

#### Describe alternatives you have considered

N/A

#### Additional context

N/A

**Comment by askulkarni2** [comment]
Not sure I understand. [enable_aws_cloudwatch_metrics](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons#input_enable_aws_cloudwatch_metrics) and [enable_aws_for_fluentbit](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons#input_enable_aws_for_fluentbit) already exists.

**Comment by DesAWSume** [comment]
Hi @askulkarni2 

Thanks for the reply, 
We have **_Amazon CloudWatch Observability_**, one of the managed addon from AWS

And it extends` enable_aws_cloudwatch_metrics` and `enable_aws_for_fluentbit` combined, ut has tracing capability that both don't have. 

So I wondering if we could add that into the features in this module as well

Thanks

**Comment by askulkarni2** [comment]
Gotcha. EKS Add-ons do not need any updates to this project. Any valid EKS add-on can be added to this list as shown here https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/f84394f91b166309ad63a8e66dc851294b268a9d/tests/complete/main.tf#L74. If you want to provide a more detailed pattern recommend you open an issue [here](https://github.com/aws-observability/terraform-aws-observability-accelerator) and work with them on this.
