### ISSUE TITLE
Usage Telemetry Opt-Out Inquiry

### ISSUE THREAD

**Issue by cisnerosk** [aws-ia/terraform-aws-eks-blueprints-addons#432]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

Hello there,

The [implementation](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1274) of `Usage Telemetry` was recently merged in and in the original issue it was noted that: "As with the Kubeflow implementation, users would have the ability to opt out of sharing telemetry data". In looking at the [PR](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/423) though, it doesn't seem like the boolean option is enabled to set this to true or false. Is the option to opt-out coming soon? I'd appreciate any guidance, thank you in advance.

**Comment by bryantbiggs** [comment]
setting it to null is the opt out
