### ISSUE TITLE
Karpetner aws_iam_service_linked_role

### ISSUE THREAD

**Issue by oscarboher** [aws-ia/terraform-aws-eks-blueprints-addons#437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Installing Karpenter in an AWS account should create the aws_iam_service_linked_role for `spot.amazonaws.com`

#### Describe the solution you would like

When karpenter is enabled, the aws_iam_service_linked_role terraform resource for `spot.amazonaws.com` is created.
If there was any reason not to create it directly, maybe it could be under a different boolean conditional.

This is required for spot instances https://karpenter.sh/v1.0/troubleshooting/#missing-service-linked-role

#### Additional context

I can do a PR for this

**Comment by bryantbiggs** [comment]
we don't create SLRs in modules because those are typically one per account across all commercial regions. if the module created this, it would cause conflicts on each subsequent deployment of additional Karpenter modules into the same account
