### ISSUE TITLE
[FEATURE] Support for passing *_helm_config to ArgoCD

### ISSUE THREAD

**Issue by kahirokunn** [aws-ia/terraform-aws-eks-blueprints-addons#59]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

passing `*_helm_config` to ArgoCD.
eg. aws_load_balancer_controller_helm_config

#### Describe the solution you would like

Add code to pass `*_helm_config` to ArgoCD.

#### Describe alternatives you have considered

It is not intuitive to change the handling of `*_helm_config` depending on whether you are using ArgoCD or not.
So I find it difficult to solve this except by passing `*_helm_config` to ArgoCD.

#### Additional context

When I wrote `aws_load_balancer_controller_helm_config`, nothing showed up in the `terraform plan`.
This only happens when using `ArgoCD`, because there is no code written to pass `*_helm_config` to `ArgoCD Application resource`.
This felt like a bug.
However, there was a possibility that the feature implementation simply had not caught up, so I created a feature request.

```terraform
aws_load_balancer_controller_helm_config = {
  values = [
    <<-EOT
    podDisruptionBudget:
      maxUnavailable: 1
    EOT
  ]
}
```

Also, I can pass helm_values by writing as follows, but the [current implementation](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/f45b1c8b6a27ea4685e96f99687c6e19bcae9649/modules/kubernetes-addons/argocd/main.tf#L62) is not sufficient, because [all values](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/96a14275555e7023288a21008ec23197ee4ccde2/modules/kubernetes-addons/aws-load-balancer-controller/locals.tf#L41) of awsLoadBalancerController will be lost in terraform's shallow merge.

```terraform
argocd_applications = {
  addons = {
    path               = "chart"
    repo_url           = local.argocd_addons_repo_url
    add_on_application = true
    values = {
      awsLoadBalancerController = {
        podDisruptionBudget = {
          maxUnavailable = 1
        }
      }
    }
  }
}
```

Also, isn't it unnatural that our value is not passed when using ArgoCD?

https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/854974d80304d736fce537699f86b8657c5fde98/modules/kubernetes-addons/aws-load-balancer-controller/values.yaml

**Comment by bryantbiggs** [comment]
thank you for the issue! At this time we are re-evaluating the integration between Terraform and GitOps operators like ArgoCD. We have removed the integration from the current project and will be tracking all feedback input in #114 while developing the next iteration of this integration

**Comment by taliesins** [comment]
The approach we took was to do a deep merge:
https://registry.terraform.io/providers/cloudposse/utils/latest

```
data "utils_deep_merge_yaml" "helm_config" {
  input = [
    yamlencode(local.default_helm_config),
    yamlencode(var.helm_config),
    yamlencode(local.addon_helm_values)
  ]
  append_list    = true
  deep_copy_list = true
}
```
