### ISSUE TITLE
Velero kubernete addon ...manage_via_gitops does not work

### ISSUE THREAD

**Issue by bmacauley** [aws-ia/terraform-aws-eks-blueprints-addons#61]
## Description

 I cannot install Velero using argocd. It always installs via helm
 
I am using the following...
  argocd_manage_add_ons  = true

Other modules are working fine and install via argocd eg externaldns

The velero module  is missing this line...

manage_via_gitops = var.manage_via_gitops

## Versions

- Module version : v4.14.0

- Terraform version:  1.1.9

**Comment by bryantbiggs** [comment]
thank you for the issue! At this time we are re-evaluating the integration between Terraform and GitOps operators like ArgoCD. We have removed the integration from the current project and will be tracking all feedback input in #114 while developing the next iteration of this integration
