### ISSUE TITLE
[Question] Should default condition operator should be StringEquals or StringLike

### ISSUE THREAD

**Issue by csantanapr** [aws-ia/terraform-aws-eks-blueprints-addons#70]
As I was updating an example I hit a problem with ArgoCD using IRSA to assume a role

Where the service account for IRSA is not deterministic and we use prefix for kubernetes service account "argocd-*"

In the v4 irsa module we use `StringLike` here https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/irsa/main.tf#L64
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::$ACCOUNT_ID:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/123"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "oidc.eks.us-west-2.amazonaws.com/id/123:sub": "system:serviceaccount:argocd:argocd-*",
                    "oidc.eks.us-west-2.amazonaws.com/id/123:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```
In the new module we use `StringEquals` here https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/main/modules/eks-blueprints-addon/variables.tf#LL312C17-L312C29
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::$ACCOUNT_ID:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/123"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-west-2.amazonaws.com/id/123:sub": "system:serviceaccount:argocd:argocd-*",
                    "oidc.eks.us-west-2.amazonaws.com/id/123:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
```

The default is now different is this by design?

**Comment by bryantbiggs** [comment]
`StringEquals` should be preferred where possible since it's a stronger/more strict check, but you can change the test condition with `assume_role_condition_test`

**Comment by csantanapr** [comment]
@bryantbiggs 
I found the variable `assume_role_condition_test` and set it to `StringLike` and it worked.

Was just double checking the change was intentional, maybe worth something to mention in the migration guide v4->v5, this is why I created the issue to recorded.
