### ISSUE TITLE
Update the External Secrets example to use fine grained IAM permissions

### ISSUE THREAD

**Issue by satveerkhurpa** [aws-ia/terraform-aws-eks-blueprints-addons#78]
## Description

In the current state the "External secrets example" creates a Cluster Secret Store with Secrets Manager as the backend and a Secrets Store with SSM as the backend. The IAM policy used for IRSA by the External Secrets operator is using a widely open permission set and does not follow security best practices. This should be updated to use fine grained IAM permissions.

Ref : https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/v4.24.0/modules/kubernetes-addons/external-secrets/data.tf
line 6 and 19.

The description for this example in the readme can also be updated to talk about the different IAM roles being created by this example to support the Cluster Secret Store and Secret Store created by the example. 

Can we also tailor our examples to follow a pattern for secrets that customer would use ? An example of the same is the dev-* pattern used by ExternalSecrets docs. Ref : https://external-secrets.io/v0.8.1/provider/aws-secrets-manager/ ( Section IAM policy )

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by askulkarni2** [comment]
@satveerkhurpa agreed on the permissions, they definitely need to be scoped down. I am not even sure if the permissions are required for the operator. As per the example, looks like they are required for `ClusterSecretStore` and `SecretStore`.
