### ISSUE TITLE
Asking for github username & password with terraform init

### ISSUE THREAD

**Issue by quickbooks2018** [aws-ia/terraform-aws-eks-blueprints-addons#91]
![image](https://user-images.githubusercontent.com/36363841/229283403-be9e5a72-4c71-4dbd-847b-cc5a01194154.png)

**Comment by quickbooks2018** [comment]
![image](https://user-images.githubusercontent.com/36363841/229286856-c6608375-a63d-4467-ab58-87c40d46044f.png)

**Comment by bryantbiggs** [comment]
I don't this is related to this project but the EKS Blueprints main project. You'll need to update to v4.27.0 to resolve this issue - see more details here https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1523
