### ISSUE TITLE
bug: karpenter addon policy causing issue

### ISSUE THREAD

**Issue by Pacobart** [aws-ia/terraform-aws-eks-blueprints-addons#99]
## Description

After successfully deploying the karpenter addon, on subsequent deployments there are times where a new terraform plan wants to destroy/create the iam policy associated with karpenter. This results in the apply failing stating `cannot create iam policy because another policy exists with the same name` error. The only way around this right now is to disable the karpenter addon, deploy (removing karpenter and iam) and then redeploying the karpenter addon again.

I propose we change this line to use a `name_prefix`: https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/karpenter/main.tf#L11

**Comment by bryantbiggs** [comment]
I suspect that you have a `depends_on` on your module which should be removed - this is known to force disruptive changes like the removal of IAM policies when changes are detected
